### ISSUE TITLE
CycleGAN

### ISSUE THREAD

**Issue by ecruz009** [aladdinpersson/Machine-Learning-Collection#37]
Hey there,

With the exception of changing the paths to make it google colab friendly, removing the val load in train, and setting load = False, I copied the files exactly as they are...but I keep getting this error. I'm not sure what I'm doing wrong. 

  0% 0/6287 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 150, in <module>
    main()
  File "train.py", line 141, in main
    train_fn(disc_H, disc_Z, gen_Z, gen_H, loader, opt_disc, opt_gen, L1, mse, d_scaler, g_scaler)
  File "train.py", line 26, in train_fn
    D_H_real = disc_H(image)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/Project1Monet/CycleGAN_from_scratch_RESNET/discriminator_model.py", line 41, in forward
    x = self.initial(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 394, in _conv_forward
    _pair(0), self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 4, 4], expected input[1, 256, 258, 5] to have 3 channels, but got 256 channels instead
  0% 0/6287 [00:02<?, ?it/s]

**Comment by ecruz009** [comment]
Nevermind! The issue was with ToTensorV2. In order to correct this error, you have to install directly from Github:
!pip install git+https://github.com/albumentations-team/albumentations.git
